---
title: "CodeBook | Tidy.csv"
output: html_document
---

#ID Variables
*Identify a unique pair of subject and acitivity* 

**SubjectID:** number index of subject's ID
**ActivityID**: Factor variable of activity's names:
  + Levels: 
      - Walking
      - Walking Upstairs
      - Walking Downstairs
      - Sitting
      - Standing
      - Laying
      - Measurement Means

#Mean variables
*Following variables are means of a measurement for each subject and activity (numeric) along X, Y & Z as indicated by the prefix (time domain body acceleration)*
  + MeanTimeBodyAccMeanX
  + MeanTimeBodyAccMeanY
  + MeanTimeBodyAccMeanZ
  + Time domain body acceleration standard deviation along X, Y, and Z:
  + MeanTimeBodyAccStdDevX
  + MeanTimeBodyAccStdDevY
  + MeanTimeBodyAccStdDevZ
  + Time domain gravity acceleration mean along X, Y, and Z:
  + MeanTimeGravityAccMeanX
  + MeanTimeGravityAccMeanY
  + MeanTimeGravityAccMeanZ
  + Time domain gravity acceleration standard deviation along X, Y, and Z:
  + MeanTimeGravityAccStdDevX
  + MeanTimeGravityAccStdDevY
  + MeanTimeGravityAccStdDevZ
  + Time domain body jerk mean along X, Y, and Z:
  + MeanTimeBodyAccJerkMeanX
  + MeanTimeBodyAccJerkMeanY
  + MeanTimeBodyAccJerkMeanZ
  + Time domain body jerk standard deviation along X, Y, and Z:
  + MeanTimeBodyAccJerkStdDevX
  + MeanTimeBodyAccJerkStdDevY
  + MeanTimeBodyAccJerkStdDevZ
  + Time domain gyroscope mean along X, Y, and Z:
  + MeanTimeBodyGyroMeanX
  + MeanTimeBodyGyroMeanY
  + MeanTimeBodyGyroMeanZ
  + Time domain gyroscope standard deviation along X, Y, and Z:
  + MeanTimeBodyGyroStdDevX
  + MeanTimeBodyGyroStdDevY
  + MeanTimeBodyGyroStdDevZ
  + Time domain gyroscope jerk mean along X, Y, and Z:
  + MeanTimeBodyGyroJerkMeanX
  + MeanTimeBodyGyroJerkMeanY
  + MeanTimeBodyGyroJerkMeanZ
  + Time domain gyroscope jerk standard deviation along X, Y, and Z:
  + MeanTimeBodyGyroJerkStdDevX
  + MeanTimeBodyGyroJerkStdDevY
  + MeanTimeBodyGyroJerkStdDevZ
  + Time domain body acceleration magnitude mean:
  + MeanTimeBodyAccMagMean
  + Time domain body acceleration magnitude standard deviation:
  + MeanTimeBodyAccMagStdDev
  + Time domain gravity acceleration magnitude mean:
  + MeanTimeGravityAccMagMean
  + Time domain gravity acceleration magnitude standard deviation:
  + MeanTimeGravityAccMagStdDev
  + Time domain body jerk magnitude mean:
  + MeanTimeBodyAccJerkMagMean
  + Time domain body jerk magnitude standard deviation:
  + MeanTimeBodyAccJerkMagStdDev
  + Time domain gyroscope magnitude mean:
  + MeanTimeBodyGyroMagMean
  + Time domain gyroscope magnitude standard deviation:
  + MeanTimeBodyGyroMagStdDev
  + Time domain gyroscope jerk magnitude mean:
  + MeanTimeBodyGyroJerkMagMean
  + Time domain gyroscope jerk magnitude standard deviation:
  + MeanTimeBodyGyroJerkMagStdDev
  + Frequency domain body acceleration mean along X, Y, and Z:
  + MeanFrequencyBodyAccMeanX
  + MeanFrequencyBodyAccMeanY
  + MeanFrequencyBodyAccMeanZ
  + Frequency domain body acceleration standard deviation along X, Y, and Z:
  + MeanFrequencyBodyAccStdDevX
  + MeanFrequencyBodyAccStdDevY
  + MeanFrequencyBodyAccStdDevZ
  + Frequency domain body jerk mean along X, Y, and Z:
  + MeanFrequencyBodyAccJerkMeanX
  + MeanFrequencyBodyAccJerkMeanY
  + MeanFrequencyBodyAccJerkMeanZ
  + Frequency domain body jerk standard deviation along X, Y, and Z:
  + MeanFrequencyBodyAccJerkStdDevX
  + MeanFrequencyBodyAccJerkStdDevY
  + MeanFrequencyBodyAccJerkStdDevZ
  + Frequency domain gyroscope mean along X, Y, and Z:
  + MeanFrequencyBodyGyroMeanX
  + MeanFrequencyBodyGyroMeanY
  + MeanFrequencyBodyGyroMeanZ
  + Frequency domain gyroscope standard deviation along X, Y, and Z:
  + MeanFrequencyBodyGyroStdDevX
  + MeanFrequencyBodyGyroStdDevY
  + MeanFrequencyBodyGyroStdDevZ
  + Frequency domain body acceleration magnitude mean:
  + MeanFrequencyBodyAccMagMean
  + Frequency domain body acceleration magnitude standard deviation:
  + MeanFrequencyBodyAccMagStdDev
  + Frequency domain body jerk magnitude mean:
  + MeanFrequencyBodyAccJerkMagMean
  + Frequency domain body jerk magnitude standard deviation:
  + MeanFrequencyBodyAccJerkMagStdDev
  + Frequency domain gyroscope magnitude mean:
  + MeanFrequencyBodyGyroMagMean
  + Frequency domain gyroscope magnitude standard deviation:
  + MeanFrequencyBodyGyroMagStdDev
  + Frequency domain gyroscope jerk magnitude mean:
  + MeanFrequencyBodyGyroJerkMagMean
  + Frequency domain gyroscope jerk magnitude standard deviation:
  + MeanFrequencyBodyGyroJerkMagStdDev